const mediadata = [
    {
      description: 'Kitten Rescue Cat Cam',
      path: 'https://youtu.be/pvEuYcM0j6M',
      thumbnail: '../images/hq720.jpg',
      category_id: 1,
    },
    {
      description: 'LIVE! Tiny dramatic newborn rescue kittens!',
      path: 'https://youtu.be/QOwC0CbtJSs',
      thumbnail: '../images/hq720-1.jpg',
      category_id: 1,
    },
    {
      description: 'LIVE 6 Newborn KittenCam 24/7 powered by PAWsitive',
      path: 'https://youtu.be/xovlH-HGyn0',
      thumbnail: '../images/hq720-2.jpg',
      category_id: 1,
    },
    {
      description: 'Kitten Cam',
      path: 'https://youtu.be/1eRbENqwHEY',
      thumbnail: '../images/hqdefault.jpg',
      category_id: 1,
    },
    {
      description: 'Rescue kitties River and Mr. Otterton need a home!',
      path: 'https://youtu.be/MsVohwdHrDA',
      thumbnail: '../images/hqdefault_live.jpg',
      category_id: 1,
    },
    {
      description: 'LIVE STREAM - Kittens',
      path: 'https://youtu.be/vXSuof3x_3Q',
      thumbnail: '../images/hqdefault-1.jpg',
      category_id: 1,
    },
    {
      description: 'Bobcat Rehab Intensive Care - Big Cat Rescue',
      path: 'https://youtu.be/6VRB2YZdes4',
      thumbnail: '../images/hqdefault-2.jpg',
      category_id: 1,
    },
    {
      description: 'Tiger Lake - Big Cat Rescue',
      path: 'https://youtu.be/NVCi9yYwRCY',
      thumbnail: '../images/hq720-3.jpg',
      category_id: 1,
    },
    {
      description: 'CARE Tiger Cub Cam',
      path: 'https://youtu.be/_Ghn-1KSlZE',
      thumbnail: '../images/hqdefault-3.jpg',
      category_id: 1,
    },
    {
      description: 'Puppy Playroom at Warrior Canine Connection',
      path: 'https://youtu.be/XLwYWCzlfIw',
      thumbnail: '../images/hqdefault-4.jpg',
      category_id: 2,
    },
    {
      description: 'LIVE STREAM Puppy Cam! Labrador puppies at play!',
      path: 'https://youtu.be/Fqhc2tjL1n8',
      thumbnail: '../images/hqdefault-5.jpg',
      category_id: 2,
    },
    {
      description: 'Full House Puppy Cam at Warrior Canine Connection',
      path: 'https://youtu.be/_nGmnWSzEvM',
      thumbnail: '../images/hq720-4.jpg',
      category_id: 2,
    },
    {
      description: 'International Wolf Center North Camera',
      path: 'https://youtu.be/SQfE_-sSdc4',
      thumbnail: '../images/hq720-5.jpg',
      category_id: 2,
    },
    {
      description: 'Best Of Wolf Cam | Playing, Fighting & Howling',
      path: 'https://youtu.be/4aqwKf6OteY',
      thumbnail: '../images/hq720-6.jpg',
      category_id: 2,
    },
    {
      description: 'Great Danes - Service Dog Project',
      path: 'https://youtu.be/o7C4_TpcNuA',
      thumbnail: '../images/hq720-7.jpg',
      category_id: 2,
    },
    {
      description: 'LIVE STREAM Puppy Cam! ',
      path: 'https://youtu.be/Fqhc2tjL1n8',
      thumbnail: '../images/hqdefault-6.jpg',
      category_id: 2,
    },
    {
      description: 'Nursery at Warrior Canine Connection',
      path: 'https://youtu.be/G0IBqtO1K28',
      thumbnail: '../images/hq720-8.jpg',
      category_id: 2,
    },
    {
      description: 'ECAD Whelping',
      path: 'https://youtu.be/8tjNccpGCTk',
      thumbnail: '../images/hq720-9.jpg',
      category_id: 2,
    },
    {
      description: 'Puppy Whelping Room at Warrior Canine Connection',
      path: 'https://youtu.be/HMafZTC8WZ0',
      thumbnail: '../images/hq720-10.jpg',
      category_id: 2,
    },
    {
      description: 'Live Jelly Cam - Monterey Bay Aquarium',
      path: 'https://youtu.be/fb8dk9w3fnQ',
      thumbnail: '../images/hq720-11.jpg',
      category_id: 3,
    },
    {
      description: 'LIVE CORAL REEF AQUARIUM',
      path: 'https://youtu.be/2ltUlpdAw-I',
      thumbnail: '../images/hq720-12.jpg',
      category_id: 3,
    },
    {
      description: 'Live Shark Cam - Monterey Bay Aquarium',
      path: 'https://youtu.be/K279u4daI-k',
      thumbnail: '../images/hq720-13.jpg',
      category_id: 3,
    },
    {
      description: 'KC Zoo Penguin Cam 4K',
      path: 'https://youtu.be/JJqXeRFsLjE',
      thumbnail: '../images/hq720-14.jpg',
      category_id: 3,
    },
    {
      description: 'Tropical Reef Camera',
      path: 'https://youtu.be/F109TZt3nRc',
      thumbnail: '../images/hq720-15.jpg',
      category_id: 3,
    },
    {
      description: 'Relaxing HD REAL Aquarium - Georgia Aquarium',
      path: 'https://youtu.be/zJ7hUvU-d2Q',
      thumbnail: '../images/hq720-16.jpg',
      category_id: 3,
    },
    {
      description: 'Live Moon Jelly Cam - Monterey Bay Aquarium',
      path: 'https://youtu.be/eecw2ImHWlM',
      thumbnail: '../images/hq720-17.jpg',
      category_id: 3,
    },
    {
      description: 'Blue Cavern',
      path: 'https://youtu.be/ogMTmdbYaPs',
      thumbnail: '../images/hq720-18.jpg',
      category_id: 3,
    },
    {
      description: 'Monterey Bay Aquarium Sea Otter Cam',
      path: 'https://youtu.be/seIooitd85w',
      thumbnail: '../images/hq720-19.jpg',
      category_id: 3,
    },
    {
      description: 'Vancouver Jellyfish Aquarium in 4K',
      path: 'https://youtu.be/b3B1Jh9Xrow',
      thumbnail: '../images/hq720-20.jpg',
      category_id: 3,
    },
    {
      description: 'Great Danes Indoor Puppy Room',
      path: 'https://youtu.be/SxhvPOvWz9w',
      thumbnail: '../images/hq720-39.jpg',
      category_id: 4,
    },
    {
      description: 'Africam Tembe Elephant Park',
      path: 'https://youtu.be/48MFrf5ADp8',
      thumbnail: '../images/hq720-37.jpg',
      category_id: 4,
    },
    {
      description: 'LIVE Bunny Cam! Baby Bunnies Playing',
      path: 'https://youtu.be/f_b_MtB2tws',
      thumbnail: '../images/hq720-36.jpg',
      category_id: 4,
    },
    {
      description: 'West End Bald Eagle Cam',
      path: 'https://youtu.be/RmmAzrAkKqI',
      thumbnail: '../images/hq720-35.jpg',
      category_id: 4,
    },
    {
      description: 'Lion Cubs Play With Spy Cam',
      path: 'https://youtu.be/8sqQqnEryvA',
      thumbnail: '../images/hq720-34.jpg',
      category_id: 4,
    },
    {
      description: 'Sloth TV',
      path: 'https://youtu.be/kQseWZfEuak',
      thumbnail: '../images/hq720-33.jpg',
      category_id: 4,
    },
    {
      description: 'Panda 24/7 HD Live At Chengdu Panda Base',
      path: 'https://youtu.be/ogpqmb1j5Jw',
      thumbnail: '../images/hq720-31.jpg',
      category_id: 4,
    },
    {
      description: 'Amur Tiger Cub Make First Public Appearance',
      path: 'https://youtu.be/P2bAa-qdDHI',
      thumbnail: '../images/hq720-29.jpg',
      category_id: 4,
    },
    {
      description: 'CARE Tiger Cub Cam ',
      path: 'https://youtu.be/_Ghn-1KSlZE',
      thumbnail: '../images/hqdefault-11.jpg',
      category_id: 4,
    },
    {
      description: 'Kitten Cabana - Big Cat Rescue',
      path: 'https://youtu.be/8chd0qHhMWQ',
      thumbnail: '../images/hq720-28.jpg',
      category_id: 4,
    },
    {
      description: 'Kitten Rescue - Baby Kittens Cam ',
      path: 'https://youtu.be/M5huFQWHyVI',
      thumbnail: '../images/hqdefault-10.jpg',
      category_id: 4,
    },
    {
      description: 'Tiny dramatic newborn rescue kittens',
      path: 'https://youtu.be/QOwC0CbtJSs',
      thumbnail: '../images/hq720-27.jpg',
      category_id: 4,
    },
    {
      description: 'Kitten Rescue Cat Cam',
      path: 'https://youtu.be/9Iup70E0Ig0',
      thumbnail: '../images/hq720-26.jpg',
      category_id: 4,
    },
    {
      description: 'GRACE Gorilla Livestream',
      path: 'https://youtu.be/672cUSe69J0',
      thumbnail: '../images/hqdefault-9.jpg',
      category_id: 4,
    },
    {
      description: 'Big Bear Bald Eagle Live Nest Cam',
      path: 'https://youtu.be/B4-L2nfGcuE',
      thumbnail: '../images/hq720-25.jpg',
      category_id: 4,
    },
    {
      description: 'Cute Baby Chicks Chirping',
      path: 'https://youtu.be/_K96qC0TzyE',
      thumbnail: '../images/hq720-24.jpg',
      category_id: 4,
    },
    {
      description: 'ECAD Whelping',
      path: 'https://youtu.be/8tjNccpGCTk',
      thumbnail: '../images/hq720-23.jpg',
      category_id: 4,
    },
    {
      description: 'Nursery at Warrior Canine Connection',
      path: 'https://youtu.be/G0IBqtO1K28',
      thumbnail: '../images/hq720-22.jpg',
      category_id: 4,
    },
    {
      description: 'LIVE STREAM Puppy Cam',
      path: 'https://youtu.be/Fqhc2tjL1n8',
      thumbnail: '../images/hqdefault-7.jpg',
      category_id: 4,
    },
    {
      description: 'Bulldog Puppy Watch - Day 69',
      path: 'https://youtu.be/sNvgGp_6_CU',
      thumbnail: '../images/hq720-21.jpg',
      category_id: 4,
    },
    {
      description: 'KC Zoo Penguin Cam 4K',
      path: 'https://youtu.be/JJqXeRFsLjE',
      thumbnail: '../images/hq720-32.jpg',
      category_id: 4,
    },
    {
      description: 'Kentucky Equine Adoption Center',
      path: 'https://youtu.be/AohUh4Wx2ps',
      thumbnail: '../images/hq720-40.jpg',
      category_id: 5,
    },
    {
      description: 'KC Zoo Penguin Cam 4K',
      path: 'https://youtu.be/JJqXeRFsLjE',
      thumbnail: '../images/hq720-41.jpg',
      category_id: 5,
    },
    {
      description: 'Hoback River @ Spotted Horse Ranch ',
      path: 'https://youtu.be/PHUxUxqwsNU',
      thumbnail: '../images/hq720-44.jpg',
      category_id: 5,
    },
    {
      description: 'Mini Horse Live Cam',
      path: 'https://youtu.be/4Nid2Ud4Uj4',
      thumbnail: '../images/hq720-43.jpg',
      category_id: 5,
    },
    {
      description: 'Donkey Hill - Service Dog Project ',
      path: 'https://youtu.be/FUkxWre2yRU',
      thumbnail: '../images/hq720-45.jpg',
      category_id: 5,
    },
    {
      description: 'Zebra LIVE | Animal Adventure Park Zebra Cam',
      path: 'https://youtu.be/gd7ik7yNppQ',
      thumbnail: '../images/hq720-46.jpg',
      category_id: 5,
    },
    {
      description: 'Zebra Cam',
      path: 'https://youtu.be/C0wKbSPi_6Y',
      thumbnail: '../images/hq720-47.jpg',
      category_id: 5,
    },
    {
      description: 'Sheep Barn Cam at Farm Sanctuary',
      path: 'https://youtu.be/tPdKmQyh6W8',
      thumbnail: '../images/hq720-48.jpg',
      category_id: 5,
    },
    {
      description: 'LIVE Baby Goats Playing OUTSIDE',
      path: 'https://youtu.be/ffx95_CvhGs',
      thumbnail: '../images/hq720-49.jpg',
      category_id: 5,
    },
    {
      description: 'Baby Goat Cam Live',
      path: 'https://youtu.be/MLjUKQeNAvw',
      thumbnail: '../images/hq720-50.jpg',
      category_id: 5,
    },
    {
      description: 'Johari & Oliver Giraffe Cam',
      path: 'https://youtu.be/xYPUtLAlzH8',
      thumbnail: '../images/hq720-51.jpg',
      category_id: 5,
    },
    {
      description: 'Live Cam Giraffe Birth at The Greenville Zoo',
      path: 'https://youtu.be/OAhMrAfBwH8',
      thumbnail: '../images/hq720-52.jpg',
      category_id: 5,
    },
    {
      description: 'NEFL Cam 1 - Live Bald Eagle Cam',
      path: 'https://youtu.be/SrKkGqkQG6M',
      thumbnail: '../images/hq720-53.jpg',
      category_id: 6,
    },
    {
      description: 'West End Bald Eagle Cam',
      path: 'https://youtu.be/RmmAzrAkKqI',
      thumbnail: '../images/hq720-54.jpg',
      category_id: 6,
    },
    {
      description: 'Decorah Eagles - North Nest ',
      path: 'https://youtu.be/eTAsANPVqB8',
      thumbnail: '../images/hq720-55.jpg',
      category_id: 6,
    },
    {
      description: 'LIVE [4K] Backyard Bird Feeder Camera',
      path: 'https://youtu.be/MtGUTs_HgcE',
      thumbnail: '../images/hq720-56.jpg',
      category_id: 6,
    },
    {
      description: 'LIVE Great Horned Owls Nesting Near Savannah, GA',
      path: 'https://youtu.be/7NFSAV15gpc',
      thumbnail: '../images/hq720-57.jpg',
      category_id: 6,
    },
    {
      description: 'Barred Owls LIVE',
      path: 'https://youtu.be/nE-qjSdc5NY',
      thumbnail: '../images/hq720-58.jpg',
      category_id: 6,
    },
    {
      description: 'Live Hummingbird Feeder Cam',
      path: 'https://youtu.be/pXe8MpU7uzk',
      thumbnail: '../images/hq720-59.jpg',
      category_id: 6,
    },
    {
      description: 'LIVE Bird Feeder Cam (4K) Gettysburg PA',
      path: 'https://youtu.be/2uabwdYMzVk',
      thumbnail: '../images/hq720-60.jpg',
      category_id: 6,
    },
    {
      description: 'LIVE HD - Hornbill, Wood hoopoes, Coucal, Loeries, Bushbaby, Genet, Fruit Bat and more',
      path: 'https://youtu.be/ODmAV8oHFhg',
      thumbnail: '../images/hqdefault-12.jpg',
      category_id: 6,
    },
    {
      description: 'Turkey Barn at Farm Sanctuary ',
      path: 'https://youtu.be/MFy7_uP45S4',
      thumbnail: '../images/hq720-61.jpg',
      category_id: 6,
    },
    {
      description: 'Ely Cathedral Peregrine Falcon webcam now live!',
      path: 'https://youtu.be/Ahj65jNL5ac',
      thumbnail: '../images/hq720-62.jpg',
      category_id: 6,
    },
    {
      description: 'Hellgate Ospreys Nest Cam',
      path: 'https://youtu.be/mUxCXCs_mR8',
      thumbnail: '../images/hq720-63.jpg',
      category_id: 6,
    },
    {
      description: 'Naked Mole Rat Live Stream at Liberty Science Center',
      path: 'https://youtu.be/9H8wbDbijRw',
      thumbnail: '../images/hq720-64.jpg',
      category_id: 7,
    },
    {
      description: 'Shark Lagoon Cam',
      path: 'https://youtu.be/LvfaMv9nbJc',
      thumbnail: '../images/hqdefault-13.jpg',
      category_id: 7,
    },
    {
      description: 'Live Shark Cam - Monterey Bay Aquarium',
      path: 'https://youtu.be/K279u4daI-k',
      thumbnail: '../images/hq720-65.jpg',
      category_id: 7,
    },
    {
      description: 'SNAKES! at the San Diego Zoo',
      path: 'https://youtu.be/PD7tfcyn7DY',
      thumbnail: '../images/hq720-66.jpg',
      category_id: 7,
    },
    {
      description: 'Lyle the Nile Crocodile LIVE',
      path: 'https://youtu.be/gb99Y3cjw1c',
      thumbnail: '../images/hq720-67.jpg',
      category_id: 7,
    },
    {
      description: 'Snake Live Cam',
      path: 'https://youtu.be/cIuKRPvO7Y0',
      thumbnail: '../images/hqdefault-14.jpg',
      category_id: 7,
    },
    {
      description: 'SNAKES! at the San Diego Zoo',
      path: 'https://youtu.be/PD7tfcyn7DY',
      thumbnail: '../images/hq720-68.jpg',
      category_id: 7,
    },
    {
      description: 'Spider Web Live Cam',
      path: 'https://youtu.be/x-ncA6q_Cbw',
      thumbnail: '../images/hq720-69.jpg',
      category_id: 7,
    },
    {
      description: 'Blue Cavern',
      path: 'https://youtu.be/ogMTmdbYaPs',
      thumbnail: '../images/hq720-70.jpg',
      category_id: 7,
    },
  ];